# Generated by Django 4.2.7 on 2023-11-13 19:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='timing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='hospital_manage.timings'),
        ),
        migrations.AlterField(
            model_name='timings',
            name='timing',
            field=models.DateField(choices=[(datetime.date(2023, 11, 14), datetime.date(2023, 11, 14)), (datetime.date(2023, 11, 15), datetime.date(2023, 11, 15)), (datetime.date(2023, 11, 16), datetime.date(2023, 11, 16)), (datetime.date(2023, 11, 17), datetime.date(2023, 11, 17)), (datetime.date(2023, 11, 18), datetime.date(2023, 11, 18)), (datetime.date(2023, 11, 19), datetime.date(2023, 11, 19)), (datetime.date(2023, 11, 20), datetime.date(2023, 11, 20)), (datetime.date(2023, 11, 21), datetime.date(2023, 11, 21)), (datetime.date(2023, 11, 22), datetime.date(2023, 11, 22)), (datetime.date(2023, 11, 23), datetime.date(2023, 11, 23))], max_length=100),
        ),
    ]
